### ISSUE TITLE
better install instructions

### ISSUE THREAD

**Issue by estebanlm** [newapplesho/twilio-smalltalk#1]
Hi!

First, congrats for your project, is very cool!

Sorry for coming to this as an issue, but it was the only way I found to contact you :)
There is a much better way to install your project: 

```
Metacello new
    baseline: 'Twilio';
    repository: 'github://newapplesho/twilio-smalltalk/pharo-repository';
    load.
```

You can even use a tag or a branch as a stable release:

```
Metacello new
    baseline: 'Twilio';
    repository: 'github://newapplesho/twilio-smalltalk:v1.1/pharo-repository';
    load.
```

(where "v1.1" is a tag or a branch you created... it could even be "master", "stable", whatever you want).

:)

I'm sorry again for the intromission, but well... lately I saw many Pharo projects on github (mine too), and I want to collaborate on improve accessibility to them.

ps: Btw... you can also create configurations as Yuriy suggests: http://blog.yuriy.tymch.uk/2015/07/pharo-and-github-versioning-revision-2.html
pps: with a configuration like that, you can copy it to MetaRepoForPharo40 (in smalltalkhub), and configuration will appear in http://catalog.pharo.org (and in image Catalog Browser), available to everybody.

**Comment by newapplesho** [comment]
Thank you for your advice.
I understand it.

``` smalltalk
Metacello new
    baseline: 'Twilio';
    repository: 'github://newapplesho/twilio-smalltalk:v0.1/pharo-repository';
    load.
```
